# Generated by Django 6.0.4 on 2026-05-04 19:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('userId', models.UUIDField(db_index=True, help_text='UUID of the requesting user (from auth_service).')),
                ('projectId', models.UUIDField(blank=True, db_index=True, help_text='UUID of the related project (from project_service), if any.', null=True)),
                ('promptType', models.CharField(choices=[('TASK_GENERATION', 'Task Generation'), ('PROJECT_SUMMARY', 'Project Summary'), ('TASK_DESCRIPTION', 'Task Description'), ('GENERIC', 'Generic')], default='GENERIC', help_text='Category of the AI prompt that was executed.', max_length=30)),
                ('tokensUsed', models.IntegerField(default=0, help_text='Total tokens consumed by this request (input + output).')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_request_logs',
                'ordering': ['-createdAt'],
                'indexes': [models.Index(fields=['userId', 'promptType'], name='idx_log_user_type'), models.Index(fields=['projectId', 'promptType'], name='idx_log_project_type')],
            },
        ),
    ]
