# Generated by Django 6.0.4 on 2026-04-23 13:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=20)),
                ('ownerId', models.UUIDField(db_index=True, help_text='UUID of the project creator, resolved from auth_service.')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('userId', models.UUIDField(db_index=True, help_text='UUID of the invited user, resolved from auth_service.')),
                ('role', models.CharField(choices=[('VIEWER', 'Viewer'), ('CONTRIBUTOR', 'Contributor'), ('MANAGER', 'Manager')], default='VIEWER', max_length=20)),
                ('joinedAt', models.DateTimeField(auto_now_add=True)),
                ('projectId', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='projects.project')),
            ],
            options={
                'db_table': 'memberships',
                'constraints': [models.UniqueConstraint(fields=('projectId', 'userId'), name='unique_project_member')],
            },
        ),
    ]
