name: Deploy NexusPlan to Oracle Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connexion SSH et Déploiement
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/NexusPlane
            git pull origin main

            cd ~/NexusPlane/chat
            git fetch origin
            git checkout nizar
            git pull origin nizar

            cd ~/NexusPlane/nexusplan-backend
            docker compose up --build -d

            docker image prune -f